# Site settings
title:       Carlos Corral
email:       emailcarloscorral@gmail.com
author:      Carlos Corral
description: Product Manager, Marketer, Thinker, Creator
baseurl:     ""
url:         "http://ccorral.github.io"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: ccorral
bitbucket_username:
stackoverflow_id:
twitter_username: carloscorral
google_plus_id:
linkedin_username: corralcarlos
angellist_username:
medium_id: carloscorral
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
